# Generated by Django 5.0.6 on 2024-11-28 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='promotion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='freight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='new',
        ),
    ]
